/*
	// Generated by Wilmer Delgado
	// 26 December - 08:12pm
*/
CREATE DATABASE JGSchool;

USE JGSchool;

CREATE TABLE Profesor(
id int identity(1,1),
nombre varchar,
dni int,
fechaNac DateTime,
telefono int,
correo varchar
constraint pk1 primary key(id)
);

CREATE TABLE Curso(
id int identity(1,1),
nombre varchar,
constraint pk2 primary key(id)
);
CREATE TABLE Estudiante(
id int identity(1,1),
nombre varchar,
dni int,
fechaNac DateTime,
telefono int,
correo varchar,
nivel varchar,
grado int,
constraint pk3 primary key(id)
);

CREATE TABLE Evaluacion(
id int identity(1,1),
descripcion varchar,
constraint pk4 primary key(id)
);

CREATE TABLE Registro(
id int identity(1,1),
idProfesor int,
idCurso int,
fechaInicio DateTime,
fechaTermino DateTime,
constraint pk5 primary key(id)
);

CREATE TABLE Notas(
id int identity(1,1),
idEstudiante int,
idEvaluacion int,
nota float,
constraint pk6 primary key(id)
);

ALTER TABLE Registro
ADD FOREIGN KEY (idProfesor) REFERENCES Profesor(id);


ALTER TABLE Registro
ADD FOREIGN KEY (idCurso) REFERENCES Curso(id);

ALTER TABLE Notas
ADD FOREIGN KEY (idEstudiante) REFERENCES Estudiante(id);


ALTER TABLE Notas
ADD FOREIGN KEY (idEvaluacion) REFERENCES Evaluacion(id);
