USE [master]
GO
/****** Object:  Database [JGSchool]    Script Date: 30/12/2020 15:49:26 ******/
CREATE DATABASE [JGSchool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JGSchool', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\JGSchool.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JGSchool_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\JGSchool_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [JGSchool] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JGSchool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JGSchool] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JGSchool] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JGSchool] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JGSchool] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JGSchool] SET ARITHABORT OFF 
GO
ALTER DATABASE [JGSchool] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [JGSchool] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JGSchool] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JGSchool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JGSchool] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JGSchool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JGSchool] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JGSchool] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JGSchool] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JGSchool] SET  ENABLE_BROKER 
GO
ALTER DATABASE [JGSchool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JGSchool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JGSchool] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JGSchool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JGSchool] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JGSchool] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JGSchool] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JGSchool] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JGSchool] SET  MULTI_USER 
GO
ALTER DATABASE [JGSchool] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JGSchool] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JGSchool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JGSchool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JGSchool] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JGSchool] SET QUERY_STORE = OFF
GO
USE [JGSchool]
GO
/****** Object:  Table [dbo].[Curso]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Curso](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](255) NULL,
	[dni] [int] NULL,
	[fechaNac] [datetime] NULL,
	[telefono] [int] NULL,
	[correo] [varchar](255) NULL,
	[nivel] [varchar](80) NULL,
	[grado] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Evaluacion]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Evaluacion](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notas]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idEstudiante] [int] NULL,
	[idEvaluacion] [int] NULL,
	[idRegistro] [int] NULL,
	[nota] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesor]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](255) NULL,
	[dni] [int] NULL,
	[fechaNac] [datetime] NULL,
	[telefono] [int] NULL,
	[correo] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Registro]    Script Date: 30/12/2020 15:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Registro](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idProfesor] [int] NULL,
	[idCurso] [int] NULL,
	[fechaInicio] [datetime] NULL,
	[fechaTermino] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Notas]  WITH CHECK ADD FOREIGN KEY([idEstudiante])
REFERENCES [dbo].[Estudiante] ([id])
GO
ALTER TABLE [dbo].[Notas]  WITH CHECK ADD FOREIGN KEY([idEvaluacion])
REFERENCES [dbo].[Evaluacion] ([id])
GO
ALTER TABLE [dbo].[Notas]  WITH CHECK ADD FOREIGN KEY([idRegistro])
REFERENCES [dbo].[Registro] ([id])
GO
ALTER TABLE [dbo].[Registro]  WITH CHECK ADD FOREIGN KEY([idCurso])
REFERENCES [dbo].[Curso] ([id])
GO
ALTER TABLE [dbo].[Registro]  WITH CHECK ADD FOREIGN KEY([idProfesor])
REFERENCES [dbo].[Profesor] ([id])
GO
USE [master]
GO
ALTER DATABASE [JGSchool] SET  READ_WRITE 
GO
